### ISSUE TITLE
_dos_setvect() in tiny model

### ISSUE THREAD

**Issue by andrewbird** [tkchia/libi86#19]
Hello @tkchia,

I have some tests in the dosemu test suite that need to set an interrupt 24 handler which are working fine in small model, but when I try to use tiny model I see this error
~~~
/tmp/test-imagedir/dXXXXs/c/fileaccs.c:49:3: error: cannot take address of far function or far static variable
   _dos_setvect(0x24, myint24);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/test-imagedir/dXXXXs/c/fileaccs.c:49:3: note: use ‘-mcmodel=small’ to allow this
ERROR
~~~

I'd prefer to use tiny model if possible, but I don't really understand why `_dos_setvect()` would seem to be expecting a near function for an interrupt handler?

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

The problem is not because `myint24` is far.  Rather the compiler does not know which segment `myint24` resides in, and it cannot really emit a relocation, because the C code is being compiled for the tiny model.

You can work around this by declaring `myint24` to be a `near_section` function.  This will tell `gcc-ia16` that `myint24` is in the same code segment as your C code, so it can simply get its address's segment from `%cs`.
```
...
extern void __far __interrupt __attribute__ ((near_section)) myint24();
...
{
  _dos_setvect(0x24, (void __far __interrupt (*)()) myint24); ...
} ...
```

(I will look into fixing `libi86` so that the type cast is not required.)

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
   Thanks for explanation and workaround. I don't suppose it's possible to make all functions appear in near_section in tiny model as they can't be anywhere else can they?

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
   Thank you for tweaking `_dos_sectvect()` to accept the near_section attribute, it reduced the changes I needed to make to my code to switch to tiny model.

Thank you!
