### ISSUE TITLE
WORDREGS?

### ISSUE THREAD

**Issue by andrewbird** [tkchia/libi86#6]
Firstly thanks again for your superb DOS compiler, it's much appreciated!
 
I'm starting to look at getting some of the software over at FreeDOS to compile with your ia16-elf-gcc compiler, so that it can hopefully be an easy environment for people to contribute to the various mini projects over at FDOS github. For this to be palatable for the FreeDOS people, I'm sure I'm going to need to keep the source as close to unmodified as possible. As an initial test I've chosen the `sort` program and my recently split out `kitten` submodule.  See https://github.com/andrewbird/sort/tree/kitten-01 . I have it compiling natively without changes on DOS with 'Turbo C' and Watcom, and also with Watcom cross compiler targetting DOS. Currently I'm looking at ia16-elf-gcc with libia86.
I see an error which looks like an incompatibility with the WORDREGS structure, see
~~~
make -C source clean ; env COMPILER=gcc ./build.sh

<snipped out some signedness warnings that appear fixable>

sort.c: In function ‘main’:
sort.c:276:24: error: ‘struct WORDREGS’ has no member named ‘flags’; did you mean ‘cflag’?
             if ((dosr.x.flags & 1) == 1) {
                        ^
make: *** [Makefile:18: sort.exe] Error 1
~~~

I note from `ia16.h` header the following
```c
/* This definition is not binary-compatible with that in Open Watcom C/C++      
   --- the latter does not have a .bp field.  */                                
struct WORDREGS                                                                 
{                                                                               
  unsigned short ax, bx, cx, dx, si, di, bp, cflag;                             
};
```

So clearly the flags field has been renamed. Since the existing source works with Watcom and TurboC what does your implementation aim to match?

**Comment by andrewbird** [comment]
Looking at other examples of `intdosx()` it seems I can check the value of `cflag` instead of doing `flags & 1`. Sorry for the noise!

**Comment by tkchia** [comment]
Thanks @andrewbird for the report anyway. :-)

After some playing around with the `sort` source code, I think I know what is going on.

`sort.c` checks for the macro `__MSDOS__`, but Open Watcom --- according to their documentation --- only defines macros `__DOS__`, `_DOS`, and `MSDOS` (argh!).  The result is that the code that uses the (nonexistent) `flags` field in `struct WORDREGS` is not actually compiled, so there is no error (!).

If you say `make CC='wcl -D__MSDOS__` instead of `make`, there should indeed be an error:
```
wcl -D__MSDOS__ -mc -oas -bt=DOS -zp1 -s -0 -wx -we -zq -fm -fe=sort sort.c kitten.c
sort.c(270): Error! E1031: Name 'flags' not found in struct/union WORDREGS
Error: Compiler returned a bad status compiling 'sort.c'
```

Anyway, `flags` is meant to hold the states of all the low order flags; while `cflag` only holds the carry flag state.  Apparently Turbo C (v2.01) has both.

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

I wonder if I should also add a "Borland compatibility mode" option for `intdos`, `intdosx`, and `struct REGS` --- so that, if a macro `_BORLANDC_SOURCE` is defined, then `struct WORDREGS` will get an extra `flags` field, just like in Turbo C, and `intdos` and `intdosx` will be implemented differently.

What do you think of this idea?

Thank you!

**Comment by andrewbird** [comment]
Hi @tkchia that sounds like good idea! One thing though, I probably wouldn't ever be able to use it as I have to make all the FDOS projects work on the Watcom compiler too. I'm sure that source changes would be the only way for me, but it could still be useful for others.

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> Hi @tkchia that sounds like good idea!

Thanks!  I will work on that.

> One thing though, I probably wouldn't ever be able to use it as I have to make all the FDOS projects work on the Watcom compiler too. I'm sure that source changes would be the only way for me, but it could still be useful for others.

Roger that.

Incidentally, in the case of `sort.c`, I think it is also necessary to get it to check for a `__DOS__` or `_DOS` macro, since (as I found out above) Open Watcom does not define `__MSDOS__`.

(I am in the process of updating `gcc-ia16` to define all these macros, and more.)

Thank you!

**Comment by andrewbird** [comment]
> Incidentally, in the case of sort.c, I think it is also necessary to get it to check for a __DOS__ or _DOS macro, since (as I found out above) Open Watcom does not define __MSDOS__.

Thanks for the heads up on that, I've now added -D__MSDOS__ to the Watcom command line. To be honest I'm not quite sure if anyone checking it out from FDOS expects it to be compilable on a platform other than DOS, so probably those #ifdefs could all go.

BTW am I okay to just `#define far __far`, will that do the right thing with say `char far *s`?

**Comment by tkchia** [comment]
Hello @andrewbird,

> so probably those #ifdefs could all go.

:-)

> BTW am I okay to just `#define far __far`, will that do the right thing with say `char far *s`?

Yes, that should _mostly_ work.

There is one thing to watch out for: in `gcc-ia16`, the `__far` keyword syntactically behaves more like the C type qualifiers `const`, `volatile`, etc.  In particular
```
char __far *a, *b;
```
will define _two_ far pointer variables, not one far pointer and one near pointer.  `gcc-ia16` will flag a warning for cases like this.

(See the issue https://github.com/tkchia/gcc-ia16/issues/11 for a longer discussion.)

Thank you!

**Comment by andrewbird** [comment]
Thanks for the explanation, it certainly helped!

**Comment by andrewbird** [comment]
Hello @tkchia , I thought I'd just let you know that I had cause to use your new _BORLANDC_SOURCE switch within FDOS/choice.  There was some code for TurboC using intdos (but required r.x.flags and ZERO_FLAG), or some inline assembler for Watcom. I think the better option was to stick with the Turbo C and your _BORLAND_SOURCE.

BTW does the ia16-elf-gcc linking step discard any unreferenced functions? I noticed that Watcom and Turbo C exes don't seem to shrink that much with unused code unless I remove the object file from the linker line.

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> Hello @tkchia , I thought I'd just let you know that I had cause to use your new _BORLANDC_SOURCE switch within FDOS/choice.

That is cool to know. :-)

> BTW does the ia16-elf-gcc linking step discard any unreferenced functions?

GCC will generally discard `static` (file-local) functions which are unused.  It does not discard exported functions though, since when compiling one module it does not generally know whether another module might want to call some of its exported functions.  (Well, there is [link-time optimization](https://gcc.gnu.org/wiki/LinkTimeOptimization), but that is a whole other kettle of fish.)

If the goal is to clean away unused exported functions from a library-like thing --- such as, say, Kitten? --- I generally prefer to maintain it as an actual library (`.lib` or `.a`), with one library module per exported function.  I think this is good to do, whether under Turbo C, Watcom, or the GNU toolchain.

Thank you!
